'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lara_Lourenço_01_06.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013anna_breaking_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013anna.breaking.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013bobby_boardwalk_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013bobby.boardwalk.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013claire_homeland_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013claire.homeland.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013jeff_newsroom_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013jeff.newsroom.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013jim_bigbang_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013jim.bigbang.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013julia_veep_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013julia.veep.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013merritt_nurse_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013merritt.nurse.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013tony_veep_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2013tony.veep.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014aaron_breaking_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014aaron.breaking.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014allison_mom_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014allison.mom.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014anna_breaking_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014anna.breaking.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014bryan_breaking_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014bryan.breaking.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014jim_bigbang_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014jim.bigbang.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014julia_veep_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014julia.veep.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014julianna_wife_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014julianna.wife.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2014ty_modern_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2014ty.modern.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015allison_mom_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015allison.mom.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015allison_mom1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015allison.mom1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015jeffrey_transparent_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015jeffrey.transparent.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015jon_madmen_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015jon.madmen.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015julia_veep_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015julia.veep.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015peter_game_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015peter.game.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015tony_veep_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015tony.veep.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015uzo_orange_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015uzo.orange.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015viola_murder_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015viola.murder.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016ben_bloodline_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016ben.bloodline.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016jeffrey_transparent_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016jeffrey.transparent.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016julia_veep_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016julia.veep.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016kate_saturday_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016kate.saturday.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016louie_baskets_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016louie.baskets.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016maggie_abbey_coa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016maggie.abbey.coa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016rami_robot_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016rami.robot.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016tatiana_orphan_prot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016tatiana.orphan.prot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _73869() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("73869", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emmy_600x300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emmy 600x300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emmy_emmys_awards_placeholder_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emmy-emmys-awards-placeholder-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emmy_nominations_revealed_game_of_thrones_dominates_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emmy-nominations-revealed-game-of-thrones-dominates-01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emmys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emmys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emmys1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emmys1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property red_plasma_tv_icon_icons_com_59528() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_plasma-tv_icon-icons.com_59528", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property television_png_tv_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("television-png-tv-0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wp1836999() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp1836999", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
